const metric = {
  id: 'api_execution_cow_kpi_solver_value_7d',
  name: 'Solver Value',
  description: 'Last 7 days',
  metricDescription: 'Total gross value generated by CoW solvers on Gnosis Chain in the last 7 complete days — the full amount found beyond the quoted or clearing price before the protocol takes its cut. Covers priceImprovement and surplus fee policies (Sep 2024+).',
  chartType: 'numberDisplay',
  format: 'formatNumberWithUSD',
  valueField: 'value',
  changeData: { enabled: true, field: 'change_pct', period: 'vs prior 7 days' },
  query: `SELECT value, change_pct FROM dbt.api_execution_cow_kpi_solver_value_7d`,
};
export default metric;
