const metric = {
  id: 'api_execution_cow_solver_value_ts',
  name: 'Solver Value Generated',
  description: 'Daily gross value found by solvers beyond reference price',
  metricDescription: 'Daily gross value generated by CoW solvers on Gnosis Chain — the full amount found beyond the reference price (quoted market price for limit orders, clearing price for market orders) before the protocol takes its cut. The protocol fee is the solver value × fee factor (typically 50%). Sep 2024+ only.',
  chartType: 'area',
  isTimeSeries: true,
  enableZoom: false,
  format: 'formatCurrencyCompact',
  smooth: true,
  symbolSize: 0,
  lineWidth: 2,
  areaOpacity: 0.6,
  xField: 'date',
  yField: 'value',
  query: `SELECT date, value FROM dbt.api_execution_cow_solver_value_ts`,
};
export default metric;
