const metric = {
  id: 'api_execution_yields_lending_activity_counts_weekly',
  name: 'Lenders & Borrowers',
  description: 'Weekly unique count',
  metricDescription: 'Weekly unique lender and borrower counts across Gnosis lending markets (Aave V3 and SparkLend) by token. The Protocol filter on the Lending tab isolates one market at a time.',
  chartType: 'bar',
  isTimeSeries: true,
  stacked: true,
  enableZoom: true,
  xField: 'date',
  yField: 'value',
  seriesField: 'activity_type',
  enableFiltering: true,
  labelField: 'token',
  globalFilterField: 'token',
  applySecondaryGlobalFilter: true,
  format: 'formatNumber',
  tooltipOrder: 'valueDesc',
  barWidth: 'auto',
  barMaxWidth: 50,
  borderRadius: [1, 1, 0, 0],
  barOpacity: 0.8,
  query: `SELECT * FROM dbt.api_execution_lending_activity_counts_weekly`,
};

export default metric;
