const metric = {
  id: 'api_execution_transactions_by_project_monthly_top5',
  name: 'Top-5 Projects by Transactions',
  description: 'Monthly number transactions per project',
  metricDescription: 'Monthly transaction counts for the top 5 projects. Useful for tracking leading project throughput over time.',
  chartType: 'bar',
  isTimeSeries: true,
  enableZoom: false,
  format: 'formatNumber',
  showTotal: true,
  barWidth: 'auto',
  barMaxWidth: 50,
  borderRadius: [1, 1, 0, 0],
  barOpacity: 0.8,
  symbolSize: 2,
  lineWidth: 2,
  xField: 'date',
  yField: 'value',
  seriesField: 'label',
  query: `SELECT * FROM dbt.api_execution_transactions_by_project_monthly_top5`,
};
export default metric;