const metric = {
  id: 'api_execution_transactions_active_accounts_by_sector_hourly',
  name: 'Initiator Accounts by Sector',
  description: 'Hourly active accounts per sector, Last 2 days',
  metricDescription: 'Hourly unique initiator accounts by sector for the recent 48-hour window. Useful for short-term activity shifts.',
  chartType: 'bar',
  isTimeSeries: true,
  enableZoom: false,
  format: 'formatNumber',
  showTotal: true,
  barWidth: 'auto',
  barMaxWidth: 50,
  borderRadius: [1, 1, 0, 0],
  barOpacity: 0.8,
  symbolSize: 2,
  lineWidth: 2,
  xField: 'date',
  yField: 'value',
  seriesField: 'label',
  query: `SELECT * FROM dbt.api_execution_transactions_active_accounts_by_sector_hourly`,
};
export default metric;